spring:
  application:
    name: exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
# logging:
#   level:
#     org.springframework: DEBUG
#     com.zaxxer.hikari: DEBUG
fixer:
    api:
      key: "1b4502a1f1391379b7f3b4aafadc4d51"
      url: "http://data.fixer.io/api/latest"

exchangerates:
   api:
     key: "8860fb47d81b5d9779e99b97dcd33939"
     url: "http://api.exchangeratesapi.io/v1/latest"

